# Generated by Django 4.2.7 on 2025-10-21 02:17

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y hora de la cita')),
                ('estado', models.CharField(choices=[('agendada', 'Agendada'), ('confirmada', 'Confirmada'), ('en_progreso', 'En progreso'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('no_show', 'No se presentó')], default='agendada', max_length=20, verbose_name='Estado de la cita')),
                ('notas', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del servicio')),
                ('descripcion', models.TextField(verbose_name='Descripción del servicio')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio')),
                ('duracion', models.PositiveIntegerField(help_text='Duración en minutos', verbose_name='Duración (minutos)')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Está activo?')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='servicios/', verbose_name='Imagen del servicio')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='WebsiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contenido', models.CharField(choices=[('inicio_titulo', 'Título de la página de inicio'), ('inicio_descripcion', 'Descripción de la página de inicio'), ('establecimiento_descripcion', 'Descripción del establecimiento'), ('establecimiento_historia', 'Historia del establecimiento'), ('establecimiento_mision', 'Misión del establecimiento'), ('establecimiento_vision', 'Visión del establecimiento'), ('contacto_telefono', 'Teléfono de contacto'), ('contacto_email', 'Email de contacto'), ('contacto_direccion', 'Dirección de contacto'), ('horarios_laborales', 'Horarios laborales')], max_length=50, unique=True, verbose_name='Tipo de contenido')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Está activo?')),
            ],
            options={
                'verbose_name': 'Contenido del sitio web',
                'verbose_name_plural': 'Contenido del sitio web',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.PositiveIntegerField(choices=[(1, '1 - Muy malo'), (2, '2 - Malo'), (3, '3 - Regular'), (4, '4 - Bueno'), (5, '5 - Excelente')], verbose_name='Calificación')),
                ('comentarios', models.TextField(blank=True, verbose_name='Comentarios adicionales')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey', to='usuarios.appointment', verbose_name='Cita relacionada')),
            ],
            options={
                'verbose_name': 'Encuesta',
                'verbose_name_plural': 'Encuestas',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('cliente', 'Cliente'), ('barbero', 'Barbero'), ('admin', 'Administrador')], default='cliente', max_length=20, verbose_name='Rol del usuario')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_users', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_users', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cortes_realizados', models.PositiveIntegerField(default=0, verbose_name='Número de cortes realizados')),
                ('cortes_para_promocion', models.PositiveIntegerField(default=5, verbose_name='Cortes necesarios para promoción')),
                ('fecha_ultimo_corte', models.DateTimeField(blank=True, null=True, verbose_name='Fecha del último corte')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to='usuarios.customuser')),
            ],
            options={
                'verbose_name': 'Perfil de cliente',
                'verbose_name_plural': 'Perfiles de clientes',
            },
        ),
        migrations.CreateModel(
            name='BarberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(blank=True, max_length=100, verbose_name='Especialidad')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción del barbero')),
                ('horario_inicio', models.TimeField(default='09:00', verbose_name='Hora de inicio del horario laboral')),
                ('horario_fin', models.TimeField(default='18:00', verbose_name='Hora de fin del horario laboral')),
                ('dias_laborales', models.JSONField(default=list, verbose_name='Días laborales (ej: ["lunes", "martes", "miercoles"])')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Está activo?')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='barber_profile', to='usuarios.customuser')),
            ],
            options={
                'verbose_name': 'Perfil de barbero',
                'verbose_name_plural': 'Perfiles de barberos',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='barbero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='usuarios.barberprofile', verbose_name='Barbero'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='usuarios.clientprofile', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='usuarios.service', verbose_name='Servicio'),
        ),
    ]
