# Generated by Django 4.2.7 on 2025-10-22 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de la imagen')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción de la imagen')),
                ('imagen', models.ImageField(upload_to='galeria/', verbose_name='Imagen')),
                ('categoria', models.CharField(choices=[('cortes', 'Cortes de cabello'), ('barbas', 'Diseños de barba'), ('afeitados', 'Afeitados'), ('instalaciones', 'Instalaciones'), ('productos', 'Productos'), ('equipo', 'Equipo profesional')], default='cortes', max_length=50, verbose_name='Categoría')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de aparición')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Está activo?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Imagen de galería',
                'verbose_name_plural': 'Imágenes de galería',
                'ordering': ['orden', 'fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=100, verbose_name='Nombre del cliente')),
                ('cliente_foto', models.ImageField(blank=True, null=True, upload_to='testimonios/', verbose_name='Foto del cliente')),
                ('testimonio', models.TextField(verbose_name='Testimonio')),
                ('calificacion', models.PositiveIntegerField(choices=[(1, '1 estrella'), (2, '2 estrellas'), (3, '3 estrellas'), (4, '4 estrellas'), (5, '5 estrellas')], verbose_name='Calificación')),
                ('servicio_recibido', models.CharField(blank=True, max_length=100, verbose_name='Servicio recibido')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de aparición')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Está activo?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Testimonio',
                'verbose_name_plural': 'Testimonios',
                'ordering': ['orden', 'fecha_creacion'],
            },
        ),
        migrations.AlterModelOptions(
            name='websitecontent',
            options={'ordering': ['orden', 'tipo_contenido'], 'verbose_name': 'Contenido del sitio web', 'verbose_name_plural': 'Contenido del sitio web'},
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='orden',
            field=models.PositiveIntegerField(default=0, verbose_name='Orden de aparición'),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Subtítulo'),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='websitecontent',
            name='contenido',
            field=models.TextField(blank=True, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='websitecontent',
            name='tipo_contenido',
            field=models.CharField(choices=[('inicio_titulo', 'Título de la página de inicio'), ('inicio_subtitulo', 'Subtítulo de la página de inicio'), ('inicio_descripcion', 'Descripción de la página de inicio'), ('establecimiento_titulo', 'Título de la sección establecimiento'), ('establecimiento_descripcion', 'Descripción del establecimiento'), ('establecimiento_historia', 'Historia del establecimiento'), ('establecimiento_mision', 'Misión del establecimiento'), ('establecimiento_vision', 'Visión del establecimiento'), ('servicios_titulo', 'Título de la sección servicios'), ('servicios_descripcion', 'Descripción de la sección servicios'), ('galeria_titulo', 'Título de la sección galería'), ('galeria_descripcion', 'Descripción de la sección galería'), ('contacto_telefono', 'Teléfono de contacto'), ('contacto_email', 'Email de contacto'), ('contacto_direccion', 'Dirección de contacto'), ('contacto_whatsapp', 'WhatsApp de contacto'), ('horarios_laborales', 'Horarios laborales'), ('horarios_lunes_viernes', 'Horarios de lunes a viernes'), ('horarios_sabado', 'Horarios de sábado'), ('horarios_domingo', 'Horarios de domingo'), ('footer_descripcion', 'Descripción del footer'), ('footer_derechos', 'Texto de derechos reservados'), ('meta_titulo', 'Título para SEO'), ('meta_descripcion', 'Descripción para SEO'), ('meta_keywords', 'Palabras clave para SEO'), ('caracteristica_1_titulo', 'Título característica 1'), ('caracteristica_1_descripcion', 'Descripción característica 1'), ('caracteristica_2_titulo', 'Título característica 2'), ('caracteristica_2_descripcion', 'Descripción característica 2'), ('caracteristica_3_titulo', 'Título característica 3'), ('caracteristica_3_descripcion', 'Descripción característica 3'), ('caracteristica_4_titulo', 'Título característica 4'), ('caracteristica_4_descripcion', 'Descripción característica 4')], max_length=50, unique=True, verbose_name='Tipo de contenido'),
        ),
    ]
