# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_galleryimage_testimonial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la sección')),
                ('tipo_seccion', models.CharField(choices=[('hero', 'Sección Hero'), ('about', 'Acerca de'), ('services', 'Servicios'), ('gallery', 'Galería'), ('testimonials', 'Testimonios'), ('contact', 'Contacto'), ('footer', 'Pie de página'), ('custom', 'Sección personalizada')], max_length=20, verbose_name='Tipo de sección')),
                ('titulo', models.CharField(blank=True, max_length=200, verbose_name='Título')),
                ('subtitulo', models.CharField(blank=True, max_length=200, verbose_name='Subtítulo')),
                ('contenido', models.TextField(blank=True, verbose_name='Contenido')),
                ('imagen_fondo', models.ImageField(blank=True, null=True, upload_to='secciones/', verbose_name='Imagen de fondo')),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to='secciones/', verbose_name='Imagen principal')),
                ('video_url', models.URLField(blank=True, verbose_name='URL del video')),
                ('boton_texto', models.CharField(blank=True, max_length=50, verbose_name='Texto del botón')),
                ('boton_url', models.CharField(blank=True, max_length=200, verbose_name='URL del botón')),
                ('color_fondo', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Color de fondo (HEX)')),
                ('color_texto', models.CharField(default='#000000', max_length=7, verbose_name='Color de texto (HEX)')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de aparición')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Está activo?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Sección de página',
                'verbose_name_plural': 'Secciones de página',
                'ordering': ['orden', 'fecha_creacion'],
            },
        ),
    ]
