# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_add_pagesection_model'),
    ]

    operations = [
        # El campo imagen ya está en el modelo WebsiteContent, solo aseguramos que existe
    ]


