# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_add_imagen_to_websitecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_configuracion', models.CharField(
                    choices=[
                        ('general', 'Configuración General'),
                        ('appearance', 'Apariencia'),
                        ('business', 'Configuración de Negocio'),
                        ('notifications', 'Notificaciones'),
                        ('social_media', 'Redes Sociales'),
                        ('seo', 'SEO y Metadata'),
                        ('payment', 'Configuración de Pagos'),
                        ('booking', 'Configuración de Reservas'),
                    ],
                    max_length=20,
                    verbose_name='Tipo de configuración'
                )),
                ('clave', models.CharField(max_length=50, unique=True, verbose_name='Clave de configuración')),
                ('valor', models.TextField(verbose_name='Valor de configuración')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Configuración del sistema',
                'verbose_name_plural': 'Configuración del sistema',
            },
        ),
    ]


