# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_add_systemsettings_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['orden', 'fecha_creacion'], 'verbose_name': 'Elemento de galería', 'verbose_name_plural': 'Elementos de galería'},
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Título del medio'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción del medio'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='galeria/', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL del video (YouTube, Vimeo, etc.)'),
        ),
    ]


