# Generated by Django 4.2.7 on 2025-11-01 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_appointment_survey_fields'),
        ('usuarios', '0008_survey_enhancements'),
    ]

    operations = [
    ]
