# Generated by Django 4.2.7 on 2025-11-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_product_appointment_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Testimonio', 'verbose_name_plural': 'Testimonios'},
        ),
        migrations.AlterModelOptions(
            name='websitecontent',
            options={'verbose_name': 'Contenido del sitio web', 'verbose_name_plural': 'Contenido del sitio web'},
        ),
        # migrations.RemoveField(
        #     model_name='galleryimage',
        #     name='categoria',
        # ),
        # migrations.RemoveField(
        #     model_name='websitecontent',
        #     name='orden',
        # ),
        # migrations.RemoveField(
        #     model_name='websitecontent',
        #     name='subtitulo',
        # ),
        # migrations.RemoveField(
        #     model_name='websitecontent',
        #     name='titulo',
        # ),
        migrations.AddField(
            model_name='galleryimage',
            name='video_file',
            field=models.FileField(blank=True, help_text='Sube un archivo MP4 directamente', null=True, upload_to='galeria/videos/', verbose_name='Archivo de video (MP4)'),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='website/', verbose_name='Imagen relacionada'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='calificacion',
            field=models.PositiveIntegerField(choices=[(1, '1 - Muy malo'), (2, '2 - Malo'), (3, '3 - Regular'), (4, '4 - Bueno'), (5, '5 - Excelente')], verbose_name='Calificación general'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='activo',
            field=models.BooleanField(db_column='activo', default=True, verbose_name='Activo/Visible'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='calificacion',
            field=models.PositiveIntegerField(choices=[(1, '1 - Muy malo'), (2, '2 - Malo'), (3, '3 - Regular'), (4, '4 - Bueno'), (5, '5 - Excelente')], db_column='calificacion', verbose_name='Calificación'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='cliente_foto',
            field=models.CharField(blank=True, db_column='cliente_foto', default='', max_length=100, verbose_name='Foto del cliente'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='cliente_nombre',
            field=models.CharField(db_column='cliente_nombre', max_length=100, verbose_name='Nombre del cliente'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, db_column='fecha_creacion', verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='orden',
            field=models.PositiveIntegerField(db_column='orden', default=0, verbose_name='Orden de visualización'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='servicio_recibido',
            field=models.CharField(blank=True, db_column='servicio_recibido', default='', max_length=100, verbose_name='Servicio recibido'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='testimonio',
            field=models.TextField(db_column='testimonio', verbose_name='Testimonio del cliente'),
        ),
        migrations.AlterField(
            model_name='websitecontent',
            name='contenido',
            field=models.TextField(verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='websitecontent',
            name='tipo_contenido',
            field=models.CharField(choices=[('inicio_titulo', 'Título de la página de inicio'), ('inicio_descripcion', 'Descripción de la página de inicio'), ('inicio_subtitulo', 'Subtítulo de la página de inicio'), ('inicio_hero_image', 'Imagen principal (Hero)'), ('hero_color_fondo', 'Color de fondo para sección hero'), ('branding_color_primario', 'Color primario de la marca'), ('branding_color_secundario', 'Color secundario de la marca'), ('establecimiento_titulo', 'Título del establecimiento'), ('establecimiento_descripcion', 'Descripción del establecimiento'), ('establecimiento_historia', 'Historia del establecimiento'), ('establecimiento_mision', 'Misión del establecimiento'), ('establecimiento_vision', 'Visión del establecimiento'), ('establecimiento_imagen', 'Imagen del establecimiento'), ('establecimiento_color_fondo', 'Color de fondo de la sección de establecimiento'), ('servicios_descripcion', 'Descripción general de servicios'), ('servicios_imagen', 'Imagen de servicios'), ('servicios_color_fondo', 'Color de fondo de la sección de servicios'), ('catalogo_titulo', 'Título del catálogo de productos'), ('catalogo_descripcion', 'Descripción del catálogo de productos'), ('productos_color_fondo', 'Color de fondo de la sección de productos'), ('ubicacion_titulo', 'Título de la sección de ubicación'), ('ubicacion_descripcion', 'Descripción de la sección de ubicación'), ('ubicacion_direccion', 'Dirección física del local'), ('ubicacion_maps_url', 'URL de Google Maps del local'), ('ubicacion_color_fondo', 'Color de fondo de la sección de ubicación'), ('contacto_telefono', 'Teléfono de contacto'), ('contacto_email', 'Email de contacto'), ('contacto_direccion', 'Dirección de contacto'), ('contacto_whatsapp', 'WhatsApp de contacto'), ('contacto_instagram', 'Instagram'), ('contacto_facebook', 'Facebook'), ('social_facebook', 'URL de Facebook'), ('social_instagram', 'URL de Instagram'), ('social_twitter', 'URL de Twitter / X'), ('horarios_laborales', 'Horarios laborales'), ('horarios_especiales', 'Horarios especiales'), ('contacto_color_fondo', 'Color de fondo de la sección contacto'), ('contacto_color_tarjeta', 'Color de las tarjetas de contacto'), ('meta_titulo', 'Título para SEO'), ('meta_descripcion', 'Descripción para SEO'), ('meta_keywords', 'Palabras clave para SEO'), ('nombre_barberia', 'Nombre de la barbería'), ('slogan', 'Slogan de la barbería'), ('descripcion_general', 'Descripción general de la barbería'), ('logo_barberia', 'Logo de la barbería'), ('features_color_fondo', 'Color de fondo de la sección de características'), ('features_color_icono', 'Color de ícono de características'), ('galeria_color_fondo', 'Color de fondo de la sección de galería'), ('galeria_descripcion', 'Descripción de la sección de galería'), ('galeria_placeholder_text', 'Mensaje cuando la galería está vacía'), ('testimonios_color_fondo', 'Color de fondo de la sección de testimonios'), ('footer_color_fondo', 'Color de fondo del pie de página'), ('footer_color_texto', 'Color de texto del pie de página'), ('footer_descripcion', 'Descripción del pie de página'), ('footer_servicio_1', 'Servicio destacado 1 en pie de página'), ('footer_servicio_2', 'Servicio destacado 2 en pie de página'), ('footer_servicio_3', 'Servicio destacado 3 en pie de página'), ('footer_servicio_4', 'Servicio destacado 4 en pie de página'), ('caracteristica_1_titulo', 'Título de característica 1'), ('caracteristica_1_descripcion', 'Descripción de característica 1'), ('caracteristica_2_titulo', 'Título de característica 2'), ('caracteristica_2_descripcion', 'Descripción de característica 2'), ('caracteristica_3_titulo', 'Título de característica 3'), ('caracteristica_3_descripcion', 'Descripción de característica 3'), ('caracteristica_4_titulo', 'Título de característica 4'), ('caracteristica_4_descripcion', 'Descripción de característica 4'), ('politica_privacidad', 'Política de privacidad'), ('terminos_condiciones', 'Términos y condiciones'), ('politica_cancelacion', 'Política de cancelación')], max_length=50, unique=True, verbose_name='Tipo de contenido'),
        ),
    ]
